# Generated by Django 4.0.1 on 2022-03-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_usr_class_delete_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usr_class',
            old_name='name',
            new_name='title',
        ),
    ]
