# Generated by Django 4.0.1 on 2022-04-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='email',
            field=models.EmailField(default=10, max_length=254),
            preserve_default=False,
        ),
    ]
