# Generated by Django 4.0.1 on 2022-04-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0002_watchlist_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
