# Generated by Django 4.0.1 on 2022-04-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0009_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
