# Generated by Django 4.0.1 on 2022-04-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0014_stock_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock_data',
        ),
    ]
