# Generated by Django 4.0.1 on 2022-04-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0017_delete_stock_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
